version: "3"
services:
  payment:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment_service
    depends_on:
      - payment_db
      - payment_kafka
    environment:
        - SPRING_PROFILES_ACTIVE=docker
        - SPRING_DATA_MONGODB_URI=mongodb://payment_db:27017/payment
        - SPRING_KAFKA_BOOTSTRAP_SERVERS=payment_kafka:9092
        - ORDER_SERVICE_URL_DOCKER=http://orderservice:8083
        - MONGO_DB_PAYMENT=mongodb://payment_db:27017/payment
    ports:
      - "8084:8084"


  payment_db:
    image: mongo:7
    container_name: payment_db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: payment

  payment_kafka:
    image: apache/kafka:4.2.0
    container_name: payment_kafka
    ports:
      - "29092:29092"
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:29092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://payment_kafka:9092,EXTERNAL://localhost:29092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@payment_kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_NUM_PARTITIONS=3
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
