
spring.data.mongodb.uri=mongodb://localhost:27017/payment

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=mongodb://localhost:27017/payment
mongodb.url=mongodb://localhost:27017

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG

order.service.url=${ORDER_SERVICE_URL}
server.port=8084
spring.kafka.bootstrap-servers=localhost:9092

logging.level.liquibase=debug