spring.data.mongodb.uri=mongodb://localhost:27017/payment

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.url=mongodb://localhost:27017/payment


logging.level.liquibase=debug