spring.application.name=PaymentService

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=payment

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.mongodb.driver.protocol.command=DEBUG